// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/kl09/counter-api"
	"sync"
)

// Ensure, that EventSenderMock does implement domain.EventSender.
// If this is not the case, regenerate this file with moq.
var _ domain.EventSender = &EventSenderMock{}

// EventSenderMock is a mock implementation of domain.EventSender.
//
//	func TestSomethingThatUsesEventSender(t *testing.T) {
//
//		// make and configure a mocked domain.EventSender
//		mockedEventSender := &EventSenderMock{
//			SendFunc: func(event domain.Event) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedEventSender in code that requires domain.EventSender
//		// and then make assertions.
//
//	}
type EventSenderMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(event domain.Event) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Event is the event argument value.
			Event domain.Event
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *EventSenderMock) Send(event domain.Event) error {
	callInfo := struct {
		Event domain.Event
	}{
		Event: event,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	if mock.SendFunc == nil {
		var (
			errOut error
		)
		return errOut
	}
	return mock.SendFunc(event)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedEventSender.SendCalls())
func (mock *EventSenderMock) SendCalls() []struct {
	Event domain.Event
} {
	var calls []struct {
		Event domain.Event
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
